import "../styles/globals.css";
import Head from "next/head";
import { useEffect } from "react";
import { initWeb3Auth } from "/utils/web3Auth";
import { GlobalStateProvider } from "/utils/store";
import { getCookie } from "/utils/cookie";
import Header from "./components/Header";

const App = ({ Component, pageProps, persistedState }) => {
   useEffect(() => {
      initWeb3Auth();
   }, []);
   return (
      <GlobalStateProvider persistedState={persistedState}>
         <Head>
            <title>Hot Swap</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Header />
         <Component {...pageProps} />
      </GlobalStateProvider>
   );
};

App.getInitialProps = async ({ ctx }) => {
   // Persists global state on page refresh
   // Check if there a state cookie saved, if cookie is available then use the cookie's value as our initial state
   const cookies = ctx?.req ? ctx.req.headers.cookie : document.cookie;
   const persistedState = (await getCookie("persistedState", cookies)) || "{}";
   console.log("persistedState", persistedState);
   return {
      persistedState: JSON.parse(persistedState),
   };
};

export default App;
