import "../styles/globals.css";
import Head from "next/head";
import { useEffect } from "react";
import { initWeb3Auth } from "/utils/web3Auth";
import { GlobalStateProvider } from "/utils/store";
import Header from "./components/Header";

function MyApp({ Component, pageProps }) {
   useEffect(() => {
      initWeb3Auth();
   }, []);
   return (
      <GlobalStateProvider>
         <Head>
            <title>Hot Swap</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Header />
         <Component {...pageProps} />
      </GlobalStateProvider>
   );
}

export default MyApp;
