import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { purchaseNft, loadNFTs } from "/utils/abi";

const Home = () => {
   const [nfts, setNfts] = useState([]);
   const [isLoading, setLoadingState] = useState(false);

   const handleLoadNfts = async () => {
      !isLoading && setLoadingState(true);
      const marketItems = await loadNFTs();
      console.log(marketItems);
      setNfts(marketItems);
      setLoadingState(false);
   };

   const handlePurchaseNft = async (nft) => {
      !isLoading && setLoadingState(true);
      await purchaseNft(nft);
      handleLoadNfts();
   };

   useEffect(() => {
      handleLoadNfts();
   }, []);

   return (
      <div className="flex justify-center">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className="" style={{ maxWidth: "1600px" }}>
            <section className="grid gap-4 pt-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">
               <h2 className="">Welcome to the Market!</h2>
               {!isLoading && !nfts.length && (
                  <h2 className="">No items currently for sale</h2>
               )}
               {!isLoading &&
                  nfts.length &&
                  nfts.map((nft, index) => (
                     <div
                        className="border shadow rounded-xl overflow-hidden"
                        key={index}
                     >
                        <Image src={nft.image} width="100%" height="100%" />
                        <div className="p-4">
                           <h3 className="h12 text-2xl font-semibold">
                              {nft.name}
                           </h3>
                           <p className="h24 p-4 overflow-hidden">
                              {nft.description}
                           </p>
                           <div>
                              <p className="text-2xl font-bold">
                                 {nft.price} Matic
                              </p>
                              <button onClick={() => handlePurchaseNft(nft)}>
                                 Buy
                              </button>
                           </div>
                        </div>
                     </div>
                  ))}
            </section>
         </main>

         <footer className=""></footer>
      </div>
   );
};

export default Home;
